### ISSUE TITLE
Endpoint request timed out

### ISSUE THREAD

**Issue by marianozicavo** [locize/locize-cli#15]
I'm running `locize sync --api-key myApiKeyHere --project-id myProjectIdHere` and getting the following error.
My locize project is brand new and has a single version called `latest`. It has two languages: `es`(reference) and `en`. 

I'm running it from a directory that has 2 directories inside: `es` and `end`. Each directory has a file for each namespace called, for example `Login.json`.

```
...
adding 1 keys in es/CreateModal...
adding 14 keys in es/CreateOfferModal...
adding 3 keys in es/CreatedProductsModal...
adding 2 keys in es/CsvDropzone...
Error: Endpoint request timed out
    at Request.request [as _callback] (/usr/local/lib/node_modules/locize-cli/sync.js:374:22)
    at Request.self.callback (/usr/local/lib/node_modules/locize-cli/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/locize-cli/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/locize-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by adrai** [comment]
strange...
Can you retry and see if this happens again?

**Comment by adrai** [comment]
Ok, will close it. But please inform us as soon as possible if you get other problems.
Btw: the last error seems more a “local” network problem.
Thanks for your patience.
And sorry again for the inconvenience.
