### ISSUE TITLE
When calling locize sync or migrate I getthe following errors

### ISSUE THREAD

**Issue by nachten** [locize/locize-cli#9]
**When calling SYNC**

othing to update for en/functionLists
adding 29 keys in en/functionUnits...
adding 3888 keys in en/functions...
adding 1017 keys in en/menus...
adding 23 keys in en/modules...
adding 12 keys in en/tabs...
adding 12 keys in en/viewTypes...
Error: Please consider to page your requests! Currently sending 1017 keys, but should send max 1000 keys!
    at Request.request [as _callback] (/usr/local/lib/node_modules/locize-cli/sync.js:371:19)

**When calling MIGRATE**

transfering latest/de/functionLists...
transfering latest/de/functionUnits...
transfering latest/de/functions...
transfering latest/de/menus...
transfering latest/de/modules...
transfering latest/de/tabs...
transfering latest/de/viewTypes...
transfering latest/en/functionLists...
transfer failed for latest/de/tabs...
Error: Project 04c3b685-8a27-442d-9f86-d6c827364c7a has no language de!
    at Request.request [as _callback] (/usr/local/lib/node_modules/locize-cli/migrate.js:85:63)

**Comment by adrai** [comment]
The migrate scenario is intended like this. But we suggest to use the sync command instead of the migrate command.
For the sync command we are going to release a new version in the next couple of minutes.

**Comment by adrai** [comment]
v4.2.1 just landed ;-)
Can you try it again?

**Comment by nachten** [comment]
That’s fast I will test it as soon as I’m back home :)
    	
    	

    	Get Outlook for iOS
    
  




On Mon, Oct 8, 2018 at 11:08 AM +0200, "Adriano Raiano" <notifications@github.com> wrote:












v4.2.1 just landed ;-)

Can you try it again?

**Comment by nachten** [comment]
Still errors

dding 1112 keys in en/common...
nothing to update for en/functionLists
nothing to update for en/functionUnits
nothing to update for en/functions
adding 1017 keys in en/menus...
nothing to update for en/modules
nothing to update for en/product
nothing to update for en/tabs
nothing to update for en/viewTypes
Error: Endpoint request timed out
    at Request.request [as _callback] (/usr/local/lib/node_modules/locize-cli/sync.js:374:22)
    at Request.self.callback (/usr/local/lib/node_modules/locize-cli/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/locize-cli/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/locize-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by nachten** [comment]
Second time I run it it worked 👍

**Comment by adrai** [comment]
Can you sent us an email to support@locize.com with a screenshot and the project-id?

**Comment by adrai** [comment]
I assume you're using en as reference language...
Did you specify the command argument `--reference-language-only false`?
Are the keys, present in the german namespaces, also present in your reference language?
